# 客户端适配器
adapter:
  go-cqhttp:
    websocket:
      ip: "127.0.0.1"
      port: 6700
      path: "/"
      admin: -1

# 处理模块
module:
  enabled:
    - "sample"
  sample:
    help: "这是一个实例模块"

# 数据服务
service:
  # 连接
  connect:
    mysql:
      enabled: false
      ip: "127.0.0.1"
      port: 3306
    sqlite:
      path: "./data/sqlite"

  sample:
    use: "sqlite"

# 网络
network:
  proxy:
    url: "http://127.0.0.1:7890"
